/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface HeyParallelSets {
    }
}
declare global {
    interface HTMLHeyParallelSetsElement extends Components.HeyParallelSets, HTMLStencilElement {
    }
    var HTMLHeyParallelSetsElement: {
        prototype: HTMLHeyParallelSetsElement;
        new (): HTMLHeyParallelSetsElement;
    };
    interface HTMLElementTagNameMap {
        "hey-parallel-sets": HTMLHeyParallelSetsElement;
    }
}
declare namespace LocalJSX {
    interface HeyParallelSets {
    }
    interface IntrinsicElements {
        "hey-parallel-sets": HeyParallelSets;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "hey-parallel-sets": LocalJSX.HeyParallelSets & JSXBase.HTMLAttributes<HTMLHeyParallelSetsElement>;
        }
    }
}
