/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { AxisConfigDict, Datum } from "./utils/data-structures/basic";
import { AxisValueSortingFunction } from "./utils/data-structures/axis";
export namespace Components {
    interface HeyParallelSets {
        "data": Datum[];
        "dimensionAndAxisLabelDict"?: AxisConfigDict<string>;
        "dimensionAndAxisMaxSegmentCountLimitDict"?: AxisConfigDict<number>;
        "dimensionAndAxisMergedSegmentLabelDict": AxisConfigDict<string>;
        "dimensionAndAxisMergedSegmentMaxRatioDict": AxisConfigDict<number>;
        "dimensionAndAxisValueSortingFunctionDict": AxisConfigDict<AxisValueSortingFunction>;
        "dimensions": string[];
        "ribbonTension": number;
    }
}
declare global {
    interface HTMLHeyParallelSetsElement extends Components.HeyParallelSets, HTMLStencilElement {
    }
    var HTMLHeyParallelSetsElement: {
        prototype: HTMLHeyParallelSetsElement;
        new (): HTMLHeyParallelSetsElement;
    };
    interface HTMLElementTagNameMap {
        "hey-parallel-sets": HTMLHeyParallelSetsElement;
    }
}
declare namespace LocalJSX {
    interface HeyParallelSets {
        "data"?: Datum[];
        "dimensionAndAxisLabelDict"?: AxisConfigDict<string>;
        "dimensionAndAxisMaxSegmentCountLimitDict"?: AxisConfigDict<number>;
        "dimensionAndAxisMergedSegmentLabelDict"?: AxisConfigDict<string>;
        "dimensionAndAxisMergedSegmentMaxRatioDict"?: AxisConfigDict<number>;
        "dimensionAndAxisValueSortingFunctionDict"?: AxisConfigDict<AxisValueSortingFunction>;
        "dimensions"?: string[];
        "ribbonTension"?: number;
    }
    interface IntrinsicElements {
        "hey-parallel-sets": HeyParallelSets;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "hey-parallel-sets": LocalJSX.HeyParallelSets & JSXBase.HTMLAttributes<HTMLHeyParallelSetsElement>;
        }
    }
}
